services:
  mongo:
    image: mongo:7.0
    container_name: notification_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      
    volumes:
      - ./data/mongo:/data/db
